### PR TITLE
Bump minimum PHP version to 5.4

### PR DESCRIPTION
**Pull request by ravage84**
Travis does not support PHP 5.3 anymore.

### CODE REVIEW

**Comment by ravage84** [comment]
Ignore the [build errors on HHVM](https://travis-ci.org/ravage84/pdepend/builds/287108186).
But it would make sense to also merge [my other PR for removing HHVM support](https://github.com/pdepend/pdepend/pull/309/).

**Comment by Soullivaneuh** [comment]
> Travis does not support PHP 5.3 anymore.

Actually, it is not really true. You can still have PHP 5.3 using `precise`: https://docs.travis-ci.com/user/reference/trusty/#PHP-images

**Comment by ravage84** [comment]
Hi @Soullivaneuh , thanks for your comment.
While this is technically true, I do not think we should use a recently EOLed version of Ubuntu on Travis just to test/support a version of PHP that has been EOLed long ago. 

https://en.wikipedia.org/wiki/Ubuntu_(operating_system)#Releases

**Comment by Soullivaneuh** [comment]
Well, this is just an information, I'm not the maintainer of this project. :wink:

**Comment by emirb** [comment]
I will close the PR as for now the project will still support 5.3. Tests failure is solved by enabling EOLed version of Ubuntu (yes, I know...) only for 5.3 in the build matrix. With a next major version it might make sense to bump minimum PHP version to at least 7. In the meantime, I'd like to see project's support for at least PHP 7 and 7.1 features (https://github.com/pdepend/pdepend/labels/PHP70, https://github.com/pdepend/pdepend/labels/PHP71) fixed.

**Pull request closed without merging**
