### PR TITLE
PHP8.1 support first class callable syntax (partial)

### PR DESCRIPTION
**Pull request by frankdekker**
Type: feature
Issue: #556 
Breaking change: no

Adds `isVariadicPlaceholder` to `ASTArguments`. 

Supports notations:
https://www.php.net/manual/en/functions.first_class_callable_syntax.php
```php
$f1 = strlen(...);
$f2 = $obj(...);  // invokable object
$f3 = $obj->method(...);
$f4 = $obj->$methodStr(...);
$f5 = Foo::staticmethod(...);
$f6 = $classStr::$staticmethodStr(...);
```
Added tests for the above notations.

These were more difficult and not part of this PR:
```php
// traditional callable using string, array
$f7 = 'strlen'(...);
$f8 = [$obj, 'method'](...);
$f9 = [Foo::class, 'staticmethod'](...);
```

### CODE REVIEW

**Comment by frankdekker** [comment]
This was more challenging than the intersection types. comments welcome :)

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
This plus the work by @kylekatarnls complets 8.1 support it looks like, and right in time before my company makes the switch to it :D

**Comment by frankdekker** [comment]
Was waiting for the checks, but seems they are stalled. Looks like some tests are failing locally. The review can wait till ive fixed those :).

**Comment by kylekatarnls** [comment]
Tests unblocked. We'll release 2.11.0 with the current state as not crashing on PHP 8.1 syntax will already help people keep PHPMD enabled and upgrade.

Maybe some of the failing tests are actually failing because ellipsis are ignored, so possibly we'll have some test to change too to align with the behavior would really expect.

But on next version, we can try to make a real support for ellipsis.

From the proposal itself having a new AST class (but extending ASTArguments sounds like a safe way to support without breaking changes. 👌

**Comment by frankdekker** [comment]
Okay, this was more difficult than expected. I managed to get an implementation that i feel confident with, and that doesn't break the entire codebase. My first approach didn't work out. Redid the implementation and added `isVariadicPlaceholder` method to `ASTArguments`. This way the standard function/method parsing still work as-is, and the ASTArguments is supplement with additional info.

**Review by AJenbo — APPROVED** [review]
Nice work, was just struggling with Variadics in PHPMD my self :)

**Review by kylekatarnls — APPROVED** [review]
With this new implementation with no new class, I also feel confident that we could put it right into 2.11.0.

**Pull request merged**
