### PR TITLE
Fix: Restrain symfony/config to ^6.0 to fix #695

### LINKED ISSUE #695: Compatibility Issue with Symfony/Config v7.0.0 in `getConfigTreeBuilder` Method
**Title**: Compatibility Issue with Symfony/Config v7.0.0 in `getConfigTreeBuilder` Method

**Environment**:
- PHP Depend version: 2.16.0
- PHP Version: 8.3.0
- Symfony/Config version: v7.0.0 (laravel/lumen-framework v10.0.2, i've tried v10.0.1 and v10.0.0 also)
- Installation type: Composer
- Operating System: Ubuntu 18.04 (Official PHP Image php:8.3-rc-fpm)

### Issue Description
There's a compatibility issue with Symfony/Config version v7.0.0 in PDepend's `getConfigTreeBuilder` method. The current implementation in `src/main/php/PDepend/DependencyInjection/Configuration.php` does not match Symfony's expected structure, resulting in a fatal error like this:

```sh
Fatal error: Declaration of PDepend\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/html/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/Configuration.php on line 77
```

The error message indicates a mismatch in the method declaration compared to the expected Symfony interface.

### Expected Behavior
To resolve this issue, I suggest to update the `getConfigTreeBuilder` method to align with Symfony's latest implementation, as sample bellow.

**Proposed Solution**:
```php
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
...
public function getConfigTreeBuilder() : TreeBuilder
{
    ...
    // replace line 84 
    $treeBuilder = new TreeBuilder('phpmd'); // here i don't go deep to understand the alias param, all my tests run succeffuly with a random string
    ...
    // replace line 109
    return $treeBuilder;
}
```

### Steps To Reproduce:
Install the dependencies and run the phpmd command to check the project like this
```sh
vendor/bin/phpmd ./app text phpmd.xml
```

### Composer Json
To help with the reproduce here my full dependencies on composer.json, the full file is attached if helps
```json
    "require": {
        "php": "^8.3",
        "intouch/newrelic": "^2.0",
        "laravel/lumen-framework": "^10.0",
        "not-empty/jwt-manager-php-lib": "^7.0",
        "not-empty/request-service-php-lib": "^7.0",
        "not-empty/response-json-php-lib": "^7.0",
        "not-empty/ulid-php-lib": "^7.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "mockery/mockery": "^1.6",
        "phpmd/phpmd": "^2.14",
        "phpunit/phpunit": "^9.6",
        "squizlabs/php_codesniffer": "^3.7"
    },
```
[composer.json](https://github.com/pdepend/pdepend/files/13501186/composer.json)

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

### PR DESCRIPTION
**Pull request by olliescase**
### New:
Type: Hotfix
Issue: #695 
Breaking change: maybe - if a project requires symfony v7 then this will no longer work. however this seems to be the safest immediate fix without breaking bwc.

Addresses issue #695 

This removes the acceptable version of v7 symfony to prevent the function definition conflict.

### Original:

Type: Hotfix
Issue: #695 
Breaking change: no  - attributes are ignored by previous versions of PHP

Addresses issue #695 

This facilitates the update of symfony/config to v7 while acknowledging backwards compatibility for the time being.

In the future the package will have to drop support for older versions of PHP in order to support the newer ones (particularly when PHP 9 comes out) however this is an intermediary step to get it functional oncemore

### CODE REVIEW

**Comment by symfonyaml** [comment]
👍

**Comment by olliescase** [comment]
Ok ignore this it doesn't work. Clears up the errors in the editor but doesn't work when actually ran

**Comment by AJenbo** [comment]
> Ok ignore this it doesn't work. Clears up the errors in the editor but doesn't work when actually ran

Could you please either close the PR or set it to draft if it's not ready to be merged

**Comment by olliescase** [comment]
Now I've updated to just limit to 6.0 as suggested by @symfonyaml - this seems to be the quickest and easiest fix

**Comment by symfonyaml** [comment]
@olliescase thank you for the update.

**Comment by olliescase** [comment]
Without breaking bwc to all previous versions the best that can happen is this is constrained to symfony/config < v6 but I do agree that there should be a new major version released soon that adopts v7 and removes bwc support

**Comment by kylekatarnls** [comment]
> Hey guys, what about all the people who need to use symfony7, cause all laravel and symfony projects are using v7 now.

Hello, PHPMD is maintained by a team of volunteers on our spare time like 99% of the OSS. It's unrealistic to expect all your tools to be compatible with all major framework as soon as they release new versions with breaking changes.

We're discussing internally how to handle this upgrade without breaking the stack of existing users.

Because we ask you to remember that requiring `"symfony/config": "^6.0"` in the semver world is not a commitment to support any major version that could come later.

Symfony choose to break whatever they want when they release a new major version, that's the meaning of it. And as a user you choose to accept those BC or to stay longer on the version 6, you're not forced to upgrade immediately.

We'll do our best to provide a correct upgrade path in a timely manner, and we'll prioritize that with a lot of other tasks that we have on our plate. (We just finish to make parsing compatible with PHP 8.3 which was released last week.)

In the meantime, if you need PHPMD for example, you can download our `phar` build on https://github.com/phpmd/phpmd/releases

As phar encapsulate dependencies you can run it with no conflict on any project.

**Comment by kylekatarnls** [comment]
Symfony 7 support implemented via #699

**Pull request closed without merging**
